sudo: required
services: 
  - docker

before_install:
  - docker build -t cratclif/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cratclif/react-test npm test -- --coverage

after_success:
  - docker build -t cratclif/multi-client ./client
  - docker build -t cratclif/multi-nginx ./nginx
  - docker build -t cratclif/multi-server ./server
  - docker build -t cratclif/multi-worker ./worker
#Login to the docker CLI
- echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
# Take thos images and push them to docker
- docker push cratclif/multi-client
- docker push cratclif/multi-nginx
- docker push cratclif/multi-server
- docker push cratclif/multi-worker
