sudo: required
services: 
  - docker

before_install:
  - docker build -t cratclif/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cratclif/react-test npm test -- --coverage

after_success:
  - docker build -t cratclif/multi-client ./client
  - docker build -t cratclif/multi-nginx ./nginx
  - docker build -t cratclif/multi-server ./server
  - docker build -t cratclif/multi-worker ./worker

